### ISSUE TITLE
Is this still maintained ?

### ISSUE THREAD

**Issue by tzumby** [gjaldon/base58check#6]
Hey @gjaldon,

I'm trying to use your library in one of my hex packages and it would be nice to get that PR that uses Erlang's :crypto library instead of sha256. 

I also worked on adding the Ripple alphabet and specify it as an option, it's not pretty yet but if you'd like I can start a PR and discuss. I can lend a hand if you need help maintaining this as well.

Cheers,

**Comment by gjaldon** [comment]
Hi @tzumby. I think you are the first to express interest in this project XD

I've already merged the PR that uses erlang's `crypto`. 

Having a Ripple alphabet as an option would be great and a PR would be welcome! :) 

There's not much activity so there's little maintenance work to be done. But you are welcome to be a maintainer if you think there's still quite some work to do on this library :)

**Comment by tzumby** [comment]
@gjaldon that's awesome, I think now I can used it in my hex package. Did you push a new version to hex by any chance ?

I'll close this issue and open another one to talk about the Ripple alphabet.
